added question 19, hypothesis and neyman-pearson
v--/se2018 pull request #1
Opened 2019-06-06 20:21 UTC by martin-varbanov96

2019-06-07 09:22 UTC, v-- requested changes
The repository has a certain structure and I would like to preserve it. A few guidelines
  * Remove the PDF from the repository. I have taken care of building all the documents available in `master` and uploading them to a file server.
  * Use the existing `make`-based build system. That means that the core source file should be named `index.tex`.
  * Add a symlink with a human-readable name to the non-existing `index.pdf` inside the `named` directory. This is necessary for exporting a directory with meaningfully-named PDF files to a file server.
  * I have set up a template, common macros and environments. Please use them.
  * Add a bibliography.
  * Add a list of topics required by the syllabus.
  * Use theorem environments instead of writing definitions and theorems as unstructured inline text.
  * Please do not submit unpolished topics. They may be incomplete, but they should be polished, i.e. there should not be things that you would normally put a `TODO` comment about.
  * Please use the `displaymath` environment instead of `$$`
  * Avoid excessive spacing

2019-06-07 09:34 UTC, v-- requested changes

2019-06-07 09:34 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +ВЪПРОС: ОСТАНА ДА НАПИШЕМ ЗА P-VALUE!!!
?

2019-06-07 09:34 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +\subsubsection{Функция на правдоподобност}
*правдободобие

2019-06-07 09:34 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +$X_n$ - извадково пространство \\
?

2019-06-07 09:34 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +Когато на $H_0$ съответства точно едно разпределение $L_0(x)$ се говори за проста основна хипотеза
`L_0` is not a distribution but the joint PDF of the observations

2019-06-07 09:34 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +$H_1 : \theta = \theta_1, \theta \in \mathbb{R}$ - Алтернативна хипотеза \\
Definitions exist for clarifying concepts, not for giving names to symbols. Please describe the concepts using prose.

2019-06-07 09:34 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +$\overline{w} \subset X_n$ - мн-во от $(x_1,..,x_n)$, т.че $H_0$ да е вярно \\
It is not clear from the definitions what does it mean for $H_0$ to be correct based solely on an n-tuple of values.

2019-06-07 09:34 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +=> $w^{*}$ е оптимална крит. обл.
The statement of the lemma is not actually a statement.

2019-06-07 09:34 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +
Please use list structures where appropriate.

2019-06-07 09:34 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +$$\frac{L_{1}(x)}{L_{0}(x)} \geq K$$
What if `L_{0}(x)` is zero?

2019-06-07 14:57 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +$X_n$ - извадково пространство \\
X_n така ни е дадено като множество, от което вземаме нещата, да не би да е вероятностно пр-во ?

2019-06-07 14:58 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +Когато на $H_0$ съответства точно едно разпределение $L_0(x)$ се говори за проста основна хипотеза
това не го разбирам

2019-06-07 14:59 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +$H_1 : \theta = \theta_1, \theta \in \mathbb{R}$ - Алтернативна хипотеза \\
Проблемът е, че няма много, Никито ей ся ми прати един учебник, там може да има нещо ;х ?

2019-06-07 15:00 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +\subsubsection{Функция на правдоподобност}
done

2019-06-07 15:00 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +$\overline{w} \subset X_n$ - мн-во от $(x_1,..,x_n)$, т.че $H_0$ да е вярно \\
тука какво се очаква да направя?

2019-06-07 15:01 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +ВЪПРОС: ОСТАНА ДА НАПИШЕМ ЗА P-VALUE!!!
\alpha-ta ни е -p-valueto ?

2019-06-07 15:03 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +=> $w^{*}$ е оптимална крит. обл.
не се занимавам с лексикални догми дали нещо е лема, твърдение, теорема, нека филолозите като оправят правописните грешки, да оправят и логическите

2019-06-07 15:09 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +
къде да направя <li> ?

2019-06-07 15:10 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +
интересно че хтмла бачка, дали има латех
$$\int_w$$

2019-06-07 19:17 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +Когато на $H_0$ съответства точно едно разпределение $L_0(x)$ се говори за проста основна хипотеза
`L_0` не е разпределение, а съвместна плътност на наблюденията

2019-06-07 19:21 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +$X_n$ - извадково пространство \\
Аз те питам какво си означил с $X_n$, защото обикновено с $X_1, \ldots, X_n$ се означават случайни величини. Ако е подмножество на $\R^n$, така го напиши, за да няма объркване.

2019-06-07 19:24 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +=> $w^{*}$ е оптимална крит. обл.
Без значение дали е лема, теорема или нещо друго, формулировката ("твърдението") на лемата е безсмислено изречение.

2019-06-07 19:25 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +
Когато изброяваш неща, както например тук

2019-06-07 19:25 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +$\overline{w} \subset X_n$ - мн-во от $(x_1,..,x_n)$, т.че $H_0$ да е вярно \\
Какво означава $H_0$ да е вярна за наредена $n$-торка?

2019-06-08 10:33 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +$X_n$ - извадково пространство \\
http://fmi.wikidot.com/prob21 смятам, че може да е вероятностно пр-во това?

2019-06-08 10:40 UTC, martin-varbanov96 commented on topics/19/19_hypot_neyman_person.tex
> +Когато на $H_0$ съответства точно едно разпределение $L_0(x)$ се говори за проста основна хипотеза
взето е от учебника на страница 252 на Янев

2019-06-08 12:36 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +Когато на $H_0$ съответства точно едно разпределение $L_0(x)$ се говори за проста основна хипотеза
Само че там в абзаца преди това е казано точно какво е $L_0$, а в цитирания от теб абзац е допусната волност на езика.

2019-06-08 12:42 UTC, v-- commented on topics/19/19_hypot_neyman_person.tex
> +$X_n$ - извадково пространство \\
1. Извадковото пространство е множеството от елементарни събития (a.k.a. генералната съвкупност) на вероятностното пространство, над което взимаме наблюдения.
2. Може просто да поясниш написаното, като добавиш $X_n \subseteq \mathbb{R}^n$, но на твое място бих сменил и буквата $X$ с нещо друго. Например $\Chi$, както е в wikidot.

2019-06-28 22:14 UTC, v-- commented
I'm closing this pull request as I have already added this topic.

2019-06-28 22:14 UTC, closed without merging